Repository TelegramBots/Telegram.Bot, pull requests merged in 2018-03, with the labels that each got.

#636 Add InvalidQueryIdException
  CHANGELOG.md
  src/Telegram.Bot/Exceptions/ApiExceptionParser.cs
  src/Telegram.Bot/Exceptions/BadRequestExceptions/Invalid Parameter/InvalidQueryIdException.cs
  test/Telegram.Bot.Tests.Integ/Exceptions/ApiExceptionsTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Mode/InlineQueryTests.cs
Labels: feature, test

#647 Cleanup apiexception
  CHANGELOG.md
  src/Telegram.Bot/Exceptions/ApiException.cs
  src/Telegram.Bot/Exceptions/ApiExceptionParser.cs
  src/Telegram.Bot/Exceptions/BadRequestException.cs
  src/Telegram.Bot/Exceptions/BadRequestExceptions/Invalid Parameter/InvalidParameterException.cs
  src/Telegram.Bot/Exceptions/BotBlockedException.cs
  src/Telegram.Bot/Exceptions/BotRestrictedException.cs
  src/Telegram.Bot/Exceptions/ForbiddenException.cs
  src/Telegram.Bot/Exceptions/MissingParameterException.cs
  src/Telegram.Bot/Exceptions/NotEnoughRightsException.cs
  src/Telegram.Bot/Exceptions/WrongChatTypeException.cs
Labels: wip

#652 Add editorconfig
  .editorconfig
  Telegram.Bot.sln
  test/Telegram.Bot.Tests.Integ/.editorconfig
  test/Telegram.Bot.Tests.Integ/Framework/.editorconfig
Labels: feature
