Repository TelegramBots/Telegram.Bot, pull requests merged in 2018-05, with the labels that each got.

#682 Fix description for LivePeriod
  src/Telegram.Bot/Types/InlineQueryResults/InlineQueryResultLocation.cs
Labels: feature

#685 Update issue templates
  .github/ISSUE_TEMPLATE/But_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Question.md
  ISSUE_TEMPLATE.md
  Telegram.Bot.sln
Labels: docs

#679 Update XML documentations
  src/Telegram.Bot/Exceptions/BadRequestException.cs
  src/Telegram.Bot/Exceptions/BadRequestExceptions/Invalid Parameter/InvalidParameterException.cs
  src/Telegram.Bot/Exceptions/ForbiddenException.cs
  src/Telegram.Bot/Exceptions/ForbiddenExceptions/ChatNotInitiatedException.cs
  src/Telegram.Bot/ITelegramBotClient.cs
  src/Telegram.Bot/Requests/Abstractions/IFormattableMessage.cs
  src/Telegram.Bot/Requests/Abstractions/IInlineMessage.cs
  src/Telegram.Bot/Requests/Abstractions/IInlineReplyMarkupMessage.cs
  src/Telegram.Bot/Requests/Abstractions/INotifiableMessage.cs
  src/Telegram.Bot/Requests/Abstractions/IReplyMarkupMessage.cs
  src/Telegram.Bot/Requests/Abstractions/IReplyMessage.cs
  src/Telegram.Bot/Requests/ParameterlessRequest.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/ICaptionInlineQueryResult.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/IInputMessageContentResult.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/ILocationInlineQueryResult.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/IThumbnailInlineQueryResult.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/IThumbnailUrlInlineQueryResult.cs
  src/Telegram.Bot/Types/InlineQueryResults/Abstractions/ITitleInlineQueryResult.cs
  src/Telegram.Bot/Types/Payments/LabeledPrice.cs
  src/Telegram.Bot/Types/ReplyMarkups/InlineKeyboardMarkup.cs
  src/Telegram.Bot/Types/ReplyMarkups/KeyboardButton.cs
  src/Telegram.Bot/Types/ReplyMarkups/ReplyKeyboardMarkup.cs
  src/Telegram.Bot/Types/WebhookInfo.cs
Labels: docs

#658 Update external references
  CHANGELOG.md
  src/Telegram.Bot/Converters/UnixDatetimeConverter.cs
  src/Telegram.Bot/Requests/Available Methods/Admin Bot/KickChatMemberRequest.cs
  src/Telegram.Bot/Requests/Available Methods/Admin Bot/RestrictChatMemberRequest.cs
  src/Telegram.Bot/Telegram.Bot.csproj
  src/Telegram.Bot/Types/ChatMember.cs
  src/Telegram.Bot/Types/Message.cs
  src/Telegram.Bot/Types/WebhookInfo.cs
  test/Telegram.Bot.Tests.Integ/Telegram.Bot.Tests.Integ.csproj
  test/Telegram.Bot.Tests.Unit/Telegram.Bot.Tests.Unit.csproj
Labels: feature

#691 Modify `OrderedFact` to support test retry
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChannelAdminBotTests.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChatMemberAdministrationTests.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/SupergroupAdminBotTests.cs
  test/Telegram.Bot.Tests.Integ/Exceptions/ApiExceptionsTests.cs
  test/Telegram.Bot.Tests.Integ/Framework/Constants.cs
  test/Telegram.Bot.Tests.Integ/Framework/ExecutionOrderAttribute.cs
  test/Telegram.Bot.Tests.Integ/Framework/OrderedFactAttribute.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestCaseOrderer.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestCaseOrderer2.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestsFixture.cs
  test/Telegram.Bot.Tests.Integ/Framework/XunitExtensions/DelayedMessageBus.cs
  test/Telegram.Bot.Tests.Integ/Framework/XunitExtensions/RetryFactDiscoverer.cs
  test/Telegram.Bot.Tests.Integ/Framework/XunitExtensions/RetryTestCase.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesExceptionTests.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesTests.cs
  test/Telegram.Bot.Tests.Integ/Getting Updates/GettingUpdatesTests.cs
  test/Telegram.Bot.Tests.Integ/Getting Updates/WebhookTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Keyboard/CallbackQueryTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Mode/InlineQueryTests.cs
  test/Telegram.Bot.Tests.Integ/Location/InlineMessageLiveLocationTests .cs
  test/Telegram.Bot.Tests.Integ/Location/LiveLocationTests.cs
  test/Telegram.Bot.Tests.Integ/Other/ChatInfoTests.cs
  test/Telegram.Bot.Tests.Integ/Other/FileDownloadTests.cs
  test/Telegram.Bot.Tests.Integ/Other/GetUserProfileTests.cs
  test/Telegram.Bot.Tests.Integ/Other/LeaveChatTests.cs
  test/Telegram.Bot.Tests.Integ/Payments/PaymentTests.cs
  test/Telegram.Bot.Tests.Integ/ReplyMarkup/PrivateChatReplyMarkupTests.cs
  test/Telegram.Bot.Tests.Integ/ReplyMarkup/ReplyMarkupTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/AlbumMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingAudioMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingContactMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingDocumentMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingPhotoMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingVenueMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/SendingVideoMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Sending Messages/TextMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Stickers/StickersTests.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/DeleteMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/EditMessageContentTests.cs
Labels: feature, test

#683 Fix InlineQuery tests
  test/Telegram.Bot.Tests.Integ/Games/GamesTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Mode/InlineQueryTests.cs
Labels: feature, test

#701 Fix: call delegates outside receive loop
  CHANGELOG.md
  src/Telegram.Bot/Telegram.Bot.csproj
  src/Telegram.Bot/TelegramBotClient.cs
Labels: bug

#702 Fix: TestApiAsync should not catch 404
  CHANGELOG.md
  src/Telegram.Bot/TelegramBotClient.cs
  test/Telegram.Bot.Tests.Integ/Getting Updates/GettingUpdatesTests.cs
Labels: bug

#700 Fix EditMessageTextAsync
  CHANGELOG.md
  src/Telegram.Bot/TelegramBotClient.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/EditMessageContentTests.cs
Labels: bug

#697 Show diagnostic messages during test run
  test/Telegram.Bot.Tests.Integ/Framework/DelayTests.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestCollectionOrderer.cs
  test/Telegram.Bot.Tests.Integ/Telegram.Bot.Tests.Integ.csproj
  test/Telegram.Bot.Tests.Integ/xunit.runner.json
Labels: feature, test

#707 Fix StickerOwnerUserId from config
  test/Telegram.Bot.Tests.Integ/Framework/ConfigurationProvider.cs
Labels: test

#706 Remove PhotoSizeConverter
  src/Telegram.Bot/Converters/PhotoSizeConverter.cs
  src/Telegram.Bot/Helpers/Extensions.cs
  src/Telegram.Bot/Types/PhotoSize.cs
  test/Telegram.Bot.Tests.Unit/Serialization/PhotoMessageSerializationTests.cs
Labels: wip

#710 Feature: chat admins are authorized testers
  docs/wikis/tests/sys-integ-tests.md
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChatMemberAdministrationTestFixture.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChatMemberAdministrationTests.cs
  test/Telegram.Bot.Tests.Integ/Framework/ConfigurationProvider.cs
  test/Telegram.Bot.Tests.Integ/Framework/Extensions.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestConfigurations.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestsFixture.cs
  test/Telegram.Bot.Tests.Integ/Framework/UpdateReceiver.cs
  test/Telegram.Bot.Tests.Integ/Payments/PaymentTests.cs
  test/Telegram.Bot.Tests.Integ/Stickers/StickersTestsFixture.cs
Labels: test

#714 Separate Interactive and Automated test cases
  .travis.yml
  test/Telegram.Bot.Tests.Integ/Admin Bot/AdminBotTestFixture.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChannelAdminBotTests.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/ChatMemberAdministrationTests.cs
  test/Telegram.Bot.Tests.Integ/Admin Bot/SupergroupAdminBotTests.cs
  test/Telegram.Bot.Tests.Integ/Exceptions/ApiExceptionsTests.cs
  test/Telegram.Bot.Tests.Integ/Exceptions/ApiExceptionsTests2.cs
  test/Telegram.Bot.Tests.Integ/Framework/Constants.cs
  test/Telegram.Bot.Tests.Integ/Framework/Fixtures/PrivateChatFixture.cs
  test/Telegram.Bot.Tests.Integ/Framework/OrderedFactAttribute.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestCollectionOrderer.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesExceptionTests.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesFixture.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesTests.cs
  test/Telegram.Bot.Tests.Integ/Games/GamesTests2.cs
  test/Telegram.Bot.Tests.Integ/Getting Updates/WebhookTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Keyboard/CallbackQueryTests.cs
  test/Telegram.Bot.Tests.Integ/Inline Mode/InlineQueryTests.cs
  test/Telegram.Bot.Tests.Integ/Location/InlineMessageLiveLocationTests .cs
  test/Telegram.Bot.Tests.Integ/Location/LiveLocationTests.cs
  test/Telegram.Bot.Tests.Integ/Other/ChatInfoTests.cs
  test/Telegram.Bot.Tests.Integ/Other/LeaveChatTests.cs
  test/Telegram.Bot.Tests.Integ/Payments/PaymentTests.cs
  test/Telegram.Bot.Tests.Integ/ReplyMarkup/PrivateChatReplyMarkupTests.cs
  test/Telegram.Bot.Tests.Integ/ReplyMarkup/ReplyMarkupTests.cs
  test/Telegram.Bot.Tests.Integ/Stickers/StickersTests.cs
  test/Telegram.Bot.Tests.Integ/Stickers/StickersTestsFixture.cs
  test/Telegram.Bot.Tests.Integ/Telegram.Bot.Tests.Integ.csproj
  test/Telegram.Bot.Tests.Integ/Update Messages/DeleteMessageTests.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/DeleteMessageTests2.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/EditMessageContentTests.cs
  test/Telegram.Bot.Tests.Integ/Update Messages/EditMessageContentTests2.cs
Labels: test
