Repository TelegramBots/Telegram.Bot, pull requests merged in 2022-04, with the labels that each got.

#1081 Fix ChatId docs
  src/Telegram.Bot/Types/ChatId.cs
Labels: 📖 docs

#1090 Remove unused parameter from PinChatMessageAsync
  src/Telegram.Bot/TelegramBotClientExtensions.ApiMethods.cs
Labels: 🐞 bug

#1087 Add options class to configure the client
  CHANGELOG.md
  src/Telegram.Bot/ITelegramBotClient.cs
  src/Telegram.Bot/TelegramBotClient.cs
  src/Telegram.Bot/TelegramBotClientExtensions.Polling.cs
  src/Telegram.Bot/TelegramBotClientOptions.cs
  test/Telegram.Bot.Tests.Integ/Framework/RetryTelegramBotClient.cs
  test/Telegram.Bot.Tests.Integ/Framework/TestsFixture.cs
  test/Telegram.Bot.Tests.Integ/Getting Updates/GettingUpdatesTests.cs
  test/Telegram.Bot.Tests.Unit/BaseUrlTests.cs
  test/Telegram.Bot.Tests.Unit/BotIdTests.cs
  test/Telegram.Bot.Tests.Unit/Polling/MockTelegramBotClient.cs
Labels: ✨ feature
